name: hf_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # remove this line if CPU-only
  - pip:
      - transformers
      - peft
      - bitsandbytes
      - accelerate
      - "datasets<3.0.0"
      - ipython
      - scipy
      - matplotlib
